mongodb:
  # Timeout (in ms) for connection attempt to mongodb
  serverselectiontimeoutms: 4000
  # db name
  dbname: "metrics"
  # Collection name for pairs
  pairs: "ohlcv_db"
  # Limit for top pairs
  pairs_top_limit: 2
  # Collection name for posts
  posts: "posts_db"
