import os
from decouple import config

# Load MongoDB env_variables
MONGODB_USER = config('MONGODB_USER')
MONGODB_PASSWORD = config('MONGODB_PASSWORD')
MONGODB_CLUSTER_ADDRESS = config('MONGODB_CLUSTER_ADDRESS')

# Load TwitterKey env_variables
TWITTER_CONSUMER_KEY = config('TW_CONSUMER_KEY')
TWITTER_CONSUMER_SECRET = config('TW_CONSUMER_SECRET')
TWITTER_ACCESS_TOKEN = config('TW_ACCESS_TOKEN')
TWITTER_ACCESS_TOKEN_SECRET = config('TW_ACCESS_TOKEN_SECRET')